### ISSUE TITLE
Nvimux bindings doesn't work at all.

### ISSUE THREAD

**Issue by GCorbel** [Vigemus/nvimux#17] opened 2017-12-23 21:43 UTC
I have a super clean vimrc file like this : 

```
filetype off

set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'BurningEther/nvimux'
call vundle#end()            " required
filetype plugin indent on    " required

let g:nvimux_prefix = '<c-a>'
let g:nvimux_override_c = 'echomsg "Open new tab" | tabe'
```
When I do <c-a>c it just do nothing. I tried with other keys but I have not results.

Commands NvimuxTermPaste, NvimuxToggleTerm and NvimuxTermRename works but not Vertical and Horizontal split.

I have Neovim 2.2.

Do I have something to do?

**Comment by hkupty** [comment] 2017-12-27 16:47
I'm sorry for taking this long to answer. I was out on holidays.

It seems there are two missing things there:
* Since nvimux is basically designed to remap keystrokes, you should prefix this override with a colon, so you're correctly mapping it to a command;
* The pipe should be escaped in order to correctly do one thing and then the other.

The final result should look like this:
`leg g:nvimux_override_c = ':echomsg "Open new tab" \| tabe'`

**Comment by GCorbel** [comment] 2017-12-28 13:39
I did a copy and paste from the doc the the command I used. I changed for the line you gave and I have the same.

**Comment by hkupty** [comment] 2017-12-28 19:27
Not really sure what's happening here. Although there was a typo in my snippet, which is already fixed, I just re-tested it and it works perfectly. 
Just a simple sanity check, so we can narrow down the cause of the bug:
By overriding a key with nvimux, you actually mean to override the combination (such as `<c-a>c` in your case). It wouldn't make much sense to create all this to do a simple `nmap c :stuff<cr>`.

As for the docs, I'll take a look at those. This should be fixed ASAP.

**Comment by GCorbel** [comment] 2017-12-28 20:51
I had some problems to install the plugin because of the doc. I had to remove [this part](https://github.com/BurningEther/nvimux/blob/master/doc/nvimux.txt#L165-L171) because `g:nvimux_quickterm_scope` present twice (I suppose). I forgot to give this information, sorry.

I'm not 100% sure about how it's suppose to work but in my case, `<c-a>q` should open a terminal, right? It doesn't. With the setup I gave, I suppose it should override `<c-a>c` and show a message in a new terminal. Am I right?

It's maybe easier to check the problem with missing commands first, it's clearer. When I do `:NvimuxVerticalSplit`, I have `not an editor command: NvimuxVerticalSplit`. I suppose this is because it's not listed [here](https://github.com/BurningEther/nvimux/blob/master/plugin/nvimux.vim). I maybe have a problem with lua support.

What you think?

**Comment by GCorbel** [comment] 2017-12-28 20:55
Lua works because I can do `:lua print(1)`.

**Comment by hkupty** [comment] 2017-12-28 21:11
> and show a message in a new terminal.

No, this should produce a message on your vim, which you'll be able to read through `:messages`. It quickly flashes on your cmd though.

> suppose this is because it's not listed here. 

What comes to my mind is that maybe the configuration doesn't work on pure VimL anymore, since this is needed:

```lua
-- Required so nvimux sets the mappings correctly
nvimux.bootstrap()
```

Also, I'm terribly sorry for misleading documentation. This wasn't updated when I switched to lua. I'm working on revamping the configuration and this will be updated as well.

**Comment by hkupty** [comment] 2017-12-28 21:12
Try running `lua require('nvimux').bootstrap()` on your init.vim. I think this will solve the problem (though through a suboptimal user experience).

**Comment by GCorbel** [comment] 2017-12-28 21:34
`lua require('nvimux').bootstrap()` makes missing commands working but the key bindings still without effects.

**Comment by hkupty** [comment] 2018-01-19 20:22
I'm thinking about dropping vim-based configuration. This should simplify the configuration and fix this issue. What do you think? (I'm sorry for taking long to retake this issue)

**Comment by GCorbel** [comment] 2018-01-20 16:13
What would be the way to configure the addon? I have no idea of how we can configure a lua addon.

**Comment by haqle** [comment] 2018-01-23 16:51
I have no experience with Lua and just started digging into it over the last hour so correct me if wrong but I think this is what happening. You set `nvim_proxy` as the metatable for `vars` to get the global variables from nvim. However, the `__index` function is only invoked if the key doesn't exist in `vars`. And since you've already set default values in vars, `__index` was never called to retrieve variables set by nvim.

**Comment by hkupty** [comment] 2018-01-23 17:09
That seems correct. I'll dig into that, but I think it's better to have a
single source of truth, which is still lua.

**Comment by haqle** [comment] 2018-01-23 17:11
I'm not sure what's the better option but at least from my point of view as an end user, I much prefer to have configurations for all my plugins in one my place.

**Comment by hkupty** [comment] 2018-01-23 17:13
Sure, that makes sense. I'll try to have a simple interface from viml to
lua, but trying to have two sources of truth is never a good idea.

Also, using the lua command to configure doesn't seem to extraneous imo (as
it is described in the README file)

**Comment by haqle** [comment] 2018-01-23 17:26
Ah, that makes sense. When I was reading that part, I didn't even know `lua` is valid command in nvim so I didn't know that you can place that in a viml file.

**Comment by hkupty** [comment] 2018-04-06 06:37
Should I close this issue? It's been a while and more refactorings for nvimux are on the way anyway..

**Comment by GCorbel** [comment] 2018-04-06 07:09
Hello,

I don't use NVim anymore. I switched to Vim8. I don't know if Nvimux should work with Vim8 but  I still have problems.

I use this rc file :

**Comment by hkupty** [comment] 2018-04-06 07:17
Nvimux is not designed or indented to work with Vim8.

**Comment by hkupty** [comment] 2018-11-16 19:35
I'm closing this issue since it's stalled. Please reopen it if the error still persists or open a new one linking to this

**Closed by hkupty** 2018-11-16 19:35 UTC
